### ISSUE TITLE
关于路由hive的问题

### ISSUE THREAD

**Issue by jzdayz** [wushengyeyouya/Hive-JDBC-Proxy#1]
你好，支持这种模型吗？比如：hive-jdbc-proxy 连接 两个hive数据源，然后客户端连接hive-proxy，根据客户端不同的账户和密码路由到我指定的hive数据源，有这个功能吗？

**Comment by jzdayz** [comment]
这边主要的代码只有scala一个类吗？

**Comment by wushengyeyouya** [comment]
> 你好，支持这种模型吗？比如：hive-jdbc-proxy 连接 两个hive数据源，然后客户端连接hive-proxy，根据客户端不同的账户和密码路由到我指定的hive数据源，有这个功能吗？

完全支持的

**Comment by wushengyeyouya** [comment]
> 这边主要的代码只有scala一个类吗？

大佬你怎么找到这个项目的，再看看，代码都已上传！

**Comment by jzdayz** [comment]
> > 这边主要的代码只有scala一个类吗？
> 
> 大佬你怎么找到这个项目的，再看看，代码都已上传！

好的，我这边试一下

**Comment by jzdayz** [comment]
> > 你好，支持这种模型吗？比如：hive-jdbc-proxy 连接 两个hive数据源，然后客户端连接hive-proxy，根据客户端不同的账户和密码路由到我指定的hive数据源，有这个功能吗？
> 
> 完全支持的

然后哥们，你这边知道es的路由工具包吗？我这边也在调研这块，主要是es和hive，mysql 和pg我这边都弄完了

**Comment by jzdayz** [comment]
> > 这边主要的代码只有scala一个类吗？
> 
> 大佬你怎么找到这个项目的，再看看，代码都已上传！

google 直接搜的到。

**Comment by wushengyeyouya** [comment]
> > > 你好，支持这种模型吗？比如：hive-jdbc-proxy 连接 两个hive数据源，然后客户端连接hive-proxy，根据客户端不同的账户和密码路由到我指定的hive数据源，有这个功能吗？
> > 
> > 
> > 完全支持的
> 
> 然后哥们，你这边知道es的路由工具包吗？我这边也在调研这块，主要是es和hive，mysql 和pg我这边都弄完了

加个微信聊吧，我微信wushengyeyy

**Comment by jzdayz** [comment]
> wushengyeyy

🆗
